module.exports = {
    phoneArena: {
        website: 'Phone Arena',
        homeUrl: 'https://www.phonearena.com',
        crawUrl: 'https://www.phonearena.com/phones/manufacturer/Samsung,Apple,Huawei,OnePlus,Xiaomi,Lenovo/',
        pageLinks: 'div.s_pager ul.clearfix li.s_last a',
        deviceUrls: '#phones div.s_listing div.s_block_4 a.s_thumb',
        deviceModel: 'div.s_breadcrumbs ul li.selected',
        physicalSize: 'div.specsicons.display',
        camera: 'div.specsicons.camera',
        chipset: 'div.specsicons.cpu',
        ram: 'div.morespecs span:first-child span',
        batteryCapacity: 'li.field-55 ul.s_lv_1 li',
    },
    gsmArena: {
        website: 'GSM Arena',
        homeUrl: 'https://www.gsmarena.com/',
        brandUrls:
        ['samsung-phones-9.php',
        'apple-phones-48.php',
        'huawei-phones-58.php',
        'oneplus-phones-95.php',
        'xiaomi-phones-80.php',
        'lenovo-phones-73.php'],
        brandLinks: 'div.brandmenu-v2 ul li a',
        pageLinks: 'div.nav-pages a:last-child',
        deviceUrls: '#review-body div.makers ul li a',
        deviceModel: 'h1.specs-phone-name-title',
        physicalSize: 'td.nfo[data-spec="displaysize"]',
        camera: 'td.nfo[data-spec="cameraprimary"]',
        chipset: 'td.nfo[data-spec="chipset"]',
        ram: 'span[data-spec="ramsize-hl"]',
        batteryCapacity: 'span[data-spec="batsize-hl"]',
    },
};
